import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/hooks/useTheme";
import { AuthProvider } from "@/hooks/useAuth";

const poppins = Poppins({
  weight: ["300", "400", "500"],
  variable: "--font-poppins",
});

const inter = Inter({
  weight: ["300", "600"],
  variable: "--font-inter",
})


export const metadata: Metadata = {
  title: {
    default: "Tugasku",
    template: "%s | Tugasku"
  },
  description: "Generated by Rafly Saputra",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${poppins.variable} ${inter.variable} overflow-x-hidden overflow-y-auto antialiased`}
      >
        <ThemeProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
